-- =============================================================================
-- 社区互助闲置平台 — 数据库 Schema (PostgreSQL 17)
-- 12 张表，全部使用 BIGINT 自增主键，每个字段附带中文注释
-- =============================================================================

-- 非破坏式初始化：仅在表不存在时创建（IF NOT EXISTS），后端重启不清空数据。
-- 后续结构变更不改本文件语义，走 SchemaMigration.java / database-operator 幂等迁移。

-- =============================================================================
-- 1. 小区表
-- =============================================================================
CREATE TABLE IF NOT EXISTS tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 小区ID
    name        VARCHAR(100) NOT NULL,                                -- 小区名称
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()                   -- 创建时间
);
COMMENT ON TABLE  tenants                IS '小区表';
COMMENT ON COLUMN tenants.id             IS '小区ID（自增主键）';
COMMENT ON COLUMN tenants.name           IS '小区名称';
COMMENT ON COLUMN tenants.created_at     IS '创建时间';

-- =============================================================================
-- 2. 楼栋表
-- =============================================================================
CREATE TABLE IF NOT EXISTS buildings (
    id           BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 楼栋ID
    tenant_id    BIGINT    NOT NULL REFERENCES tenants(id),              -- 所属小区ID
    building_no  INTEGER   NOT NULL,                                     -- 楼栋号（如 3，展示时前端/后端拼"3栋"）
    created_at   TIMESTAMP NOT NULL DEFAULT NOW()                        -- 创建时间
);
COMMENT ON TABLE  buildings              IS '楼栋表';
COMMENT ON COLUMN buildings.id           IS '楼栋ID（自增主键）';
COMMENT ON COLUMN buildings.tenant_id    IS '所属小区ID，外键→tenants.id';
COMMENT ON COLUMN buildings.building_no  IS '楼栋号（数值，展示时拼"栋"后缀）';
COMMENT ON COLUMN buildings.created_at   IS '创建时间';

-- =============================================================================
-- 3. 单元表
-- =============================================================================
CREATE TABLE IF NOT EXISTS units (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 单元ID
    building_id BIGINT    NOT NULL REFERENCES buildings(id),            -- 所属楼栋ID
    unit_no     INTEGER   NOT NULL,                                     -- 单元号（如 2，展示时拼"单元"）
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()                        -- 创建时间
);
COMMENT ON TABLE  units                   IS '单元表';
COMMENT ON COLUMN units.id                IS '单元ID（自增主键）';
COMMENT ON COLUMN units.building_id       IS '所属楼栋ID，外键→buildings.id';
COMMENT ON COLUMN units.unit_no           IS '单元号（数值，展示时拼"单元"后缀）';
COMMENT ON COLUMN units.created_at        IS '创建时间';

-- =============================================================================
-- 4. 房间表
-- =============================================================================
CREATE TABLE IF NOT EXISTS rooms (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 房间ID
    unit_id     BIGINT      NOT NULL REFERENCES units(id),                -- 所属单元ID
    room_number VARCHAR(10) NOT NULL,                                     -- 房间号（如 1501）
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW()                        -- 创建时间
);
COMMENT ON TABLE  rooms                   IS '房间表';
COMMENT ON COLUMN rooms.id                IS '房间ID（自增主键）';
COMMENT ON COLUMN rooms.unit_id           IS '所属单元ID，外键→units.id';
COMMENT ON COLUMN rooms.room_number       IS '房间号';
COMMENT ON COLUMN rooms.created_at        IS '创建时间';

-- =============================================================================
-- 5. 用户表
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 用户ID
    room_id         BIGINT       REFERENCES rooms(id),                          -- 房间ID
    tenant_id       BIGINT,                                                      -- 所属小区ID
    openid          VARCHAR(64)  UNIQUE,                                         -- 微信OpenID
    username        VARCHAR(50)  UNIQUE,                                         -- 管理员用户名
    password_hash   VARCHAR(255),                                                -- 密码哈希（BCrypt）
    user_type       VARCHAR(20)  NOT NULL DEFAULT 'owner',                       -- 用户类型：'owner'(业主)/'tenant'(租客)/'admin'(普通管理员)/'super_admin'(超级管理员)
    name            VARCHAR(50),                                                 -- 姓名/昵称
    phone           VARCHAR(11),                                                 -- 手机号，11位
    phone_verified  BOOLEAN      NOT NULL DEFAULT FALSE,                         -- 手机号是否已验证
    avatar_url      VARCHAR(500),                                                -- 头像URL
    auth_status     VARCHAR(20)  NOT NULL DEFAULT 'pending',                     -- 认证状态：pending(待审核)/approved(已通过)/rejected(已拒绝)/registering(注册中)/banned(已封禁)
    banned_reason   VARCHAR(200),                                                -- 封禁原因，最多200字，仅auth_status=banned时有值
    doc_images      TEXT,                                                        -- 证件照片URL（JSON数组）
    reject_reason   VARCHAR(200),                                                -- 认证拒绝原因，最多200字，仅auth_status=rejected时有值
    token_version   INTEGER      NOT NULL DEFAULT 0,                             -- 令牌版本号（单会话登录控制）
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),                         -- 更新时间
    UNIQUE (phone, tenant_id),                                                  -- 同一小区内手机号唯一
    UNIQUE (room_id, user_type)                                                 -- 同一房间同一身份只能注册一个住户（业主与租客可并存）
);
COMMENT ON TABLE  users                     IS '用户表，存储所有用户（C端住户/B端管理员）';
COMMENT ON COLUMN users.id                  IS '用户ID（自增主键）';
COMMENT ON COLUMN users.room_id             IS '房间ID，外键→rooms.id，同一房间同一身份只能注册一个住户（业主与租客可并存）';
COMMENT ON COLUMN users.tenant_id           IS '所属小区ID，外键→tenants.id';
COMMENT ON COLUMN users.openid              IS '微信OpenID，C端用户唯一标识';
COMMENT ON COLUMN users.username            IS 'B端管理员用户名，管理员登录用';
COMMENT ON COLUMN users.password_hash       IS '密码哈希，BCrypt加密';
COMMENT ON COLUMN users.user_type           IS '用户类型：''owner''(业主)/''tenant''(租客)/''admin''(普通管理员)/''super_admin''(超级管理员)';
COMMENT ON COLUMN users.name                IS '姓名/昵称';
COMMENT ON COLUMN users.phone               IS '手机号，11位';
COMMENT ON COLUMN users.phone_verified      IS '手机号是否已验证：false(未验证)/true(已验证)';
COMMENT ON COLUMN users.avatar_url          IS '头像URL';
COMMENT ON COLUMN users.auth_status         IS '认证状态：pending(待审核)/approved(已通过)/rejected(已拒绝)/registering(注册中)/banned(已封禁)';
COMMENT ON COLUMN users.banned_reason       IS '封禁原因，最多200字，仅auth_status=banned时有值';
COMMENT ON COLUMN users.doc_images          IS '证件照片URL（JSON数组），注册时上传的房产证/租房合同';
COMMENT ON COLUMN users.reject_reason       IS '认证拒绝原因，最多200字，仅auth_status=rejected时有值';
COMMENT ON COLUMN users.token_version       IS '令牌版本号（单会话登录控制）';
COMMENT ON COLUMN users.created_at          IS '创建时间';
COMMENT ON COLUMN users.updated_at          IS '更新时间';

-- =============================================================================
-- 6. 闲置物品表
-- =============================================================================
CREATE TABLE IF NOT EXISTS idle_items (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 物品ID
    user_id         BIGINT         NOT NULL REFERENCES users(id),                  -- 发布用户ID
    tenant_id       BIGINT         NOT NULL REFERENCES tenants(id),               -- 所属小区ID
    post_type       VARCHAR(10)    NOT NULL DEFAULT 'LEND',                        -- 发布类型：LEND(闲置借出)/WANTED(需求借入)
    title           VARCHAR(100)   NOT NULL,                                       -- 标题
    description     VARCHAR(200),                                                  -- 描述，最多200字
    category        VARCHAR(20)    NOT NULL,                                       -- 分类：工具/电子产品/书籍/家居/运动/玩具/服饰/其他
    condition       VARCHAR(10)    NOT NULL DEFAULT 'normal',                      -- 成色：like-new(几乎全新)/normal(正常使用痕迹)/worn(有明显磨损)
    price           DECIMAL(10,2)  NOT NULL DEFAULT 0,                             -- 参考价格（元）
    images          TEXT,                                                          -- 图片URL（JSON数组），最多4张
    max_duration    INTEGER        DEFAULT 7,                                      -- 最大借出时长值
    duration_unit   VARCHAR(10)    NOT NULL DEFAULT 'day',                         -- 时长单位：day(天)/hour(小时)
    pickup_method   VARCHAR(30)    NOT NULL DEFAULT 'self_pickup',                 -- 取件方式：self_pickup(需自提)/both(自提或送上门)
    status          VARCHAR(20)    NOT NULL DEFAULT 'online',                      -- 状态：online(在线)/draft(草稿)/pending_review(待AI审核)/pending(待审批)/active(进行中)/completed(已完成)/offline(已下架)
    delist_reason   VARCHAR(200),                                                  -- 统一下架原因：AI审核原因、管理员驳回/下架原因、用户自行下架原因
    is_proxy        BOOLEAN        NOT NULL DEFAULT FALSE,                         -- 是否物业代发：false(否)/true(是)
    created_at      TIMESTAMP      NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at      TIMESTAMP      NOT NULL DEFAULT NOW()                          -- 更新时间
);
COMMENT ON TABLE  idle_items                 IS '闲置物品表，C端用户发布的闲置借出/需求借入信息';
COMMENT ON COLUMN idle_items.id              IS '物品ID（自增主键）';
COMMENT ON COLUMN idle_items.user_id         IS '发布用户ID，外键→users.id';
COMMENT ON COLUMN idle_items.tenant_id       IS '所属小区ID，外键→tenants.id，用于按小区隔离数据';
COMMENT ON COLUMN idle_items.post_type       IS '发布类型：LEND(闲置借出)/WANTED(需求借入)';
COMMENT ON COLUMN idle_items.title           IS '标题';
COMMENT ON COLUMN idle_items.description     IS '描述，物品现状、使用痕迹、附件清单等，最多200字';
COMMENT ON COLUMN idle_items.category        IS '分类：工具/电子产品/书籍/家居/运动/玩具/服饰/其他（用户自定义）';
COMMENT ON COLUMN idle_items.condition       IS '成色：like-new(几乎全新)/normal(正常使用痕迹)/worn(有明显磨损)';
COMMENT ON COLUMN idle_items.price           IS '参考价格（元），用于损坏赔偿基准';
COMMENT ON COLUMN idle_items.images          IS '图片URL（JSON数组格式），最多4张';
COMMENT ON COLUMN idle_items.max_duration    IS '最大借出时长值，如7天=7';
COMMENT ON COLUMN idle_items.duration_unit   IS '时长单位：day(天)/hour(小时)';
COMMENT ON COLUMN idle_items.pickup_method   IS '取件方式：self_pickup(需自提)/both(自提或送上门)';
COMMENT ON COLUMN idle_items.status          IS '状态：online(在线)/draft(草稿)/pending_review(待AI审核)/pending(待审批)/active(进行中)/completed(已完成)/offline(已下架)';
COMMENT ON COLUMN idle_items.delist_reason   IS '统一下架原因：AI审核原因、管理员驳回/下架原因、用户自行下架原因';
COMMENT ON COLUMN idle_items.is_proxy        IS '是否物业代发：false(否)/true(是)';
COMMENT ON COLUMN idle_items.created_at      IS '创建时间';
COMMENT ON COLUMN idle_items.updated_at      IS '更新时间';

-- =============================================================================
-- 7. 求助信息表
-- =============================================================================
CREATE TABLE IF NOT EXISTS help_requests (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 求助ID
    user_id         BIGINT      NOT NULL REFERENCES users(id),                  -- 发布用户ID
    tenant_id       BIGINT      NOT NULL REFERENCES tenants(id),               -- 所属小区ID
    title           VARCHAR(100) NOT NULL,                                      -- 标题
    description     VARCHAR(200),                                               -- 描述，最多200字
    category        VARCHAR(20) NOT NULL,                                       -- 分类：维修/陪护/代取/搬运/辅导/遛宠/烹饪/其他
    is_urgent       BOOLEAN     NOT NULL DEFAULT FALSE,                         -- 是否紧急：false(普通)/true(紧急)
    time_start      TIMESTAMP,                                                  -- 预计开始时间，可选
    time_end        TIMESTAMP,                                                  -- 预计结束时间，可选
    images          TEXT,                                                       -- 图片URL（JSON数组格式）
    status          VARCHAR(20) NOT NULL DEFAULT 'online',                      -- 状态：online(在线)/draft(草稿)/pending_review(待AI审核)/pending(待审批)/active(进行中)/completed(已完成)/offline(已下架)
    delist_reason   VARCHAR(200),                                               -- 统一下架原因：AI审核原因、管理员驳回/下架原因、用户自行下架原因
    is_proxy        BOOLEAN     NOT NULL DEFAULT FALSE,                         -- 是否物业代发：false(否)/true(是)
    location        VARCHAR(200),                                               -- 求助地点
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at      TIMESTAMP   NOT NULL DEFAULT NOW()                          -- 更新时间
);
COMMENT ON TABLE  help_requests               IS '求助信息表，C端用户发布的技能求助信息';
COMMENT ON COLUMN help_requests.id            IS '求助ID（自增主键）';
COMMENT ON COLUMN help_requests.user_id       IS '发布用户ID，外键→users.id';
COMMENT ON COLUMN help_requests.tenant_id     IS '所属小区ID，外键→tenants.id，用于按小区隔离数据';
COMMENT ON COLUMN help_requests.title         IS '标题';
COMMENT ON COLUMN help_requests.description   IS '描述，详细说明需要什么帮助，最多200字';
COMMENT ON COLUMN help_requests.category      IS '分类：维修/陪护/代取/搬运/辅导/遛宠/烹饪/其他（用户自定义）';
COMMENT ON COLUMN help_requests.is_urgent     IS '是否紧急：false(普通)/true(紧急)';
COMMENT ON COLUMN help_requests.time_start    IS '预计开始时间，可选';
COMMENT ON COLUMN help_requests.time_end      IS '预计结束时间，可选';
COMMENT ON COLUMN help_requests.images        IS '图片URL（JSON数组格式）';
COMMENT ON COLUMN help_requests.status        IS '状态：online(在线)/draft(草稿)/pending_review(待AI审核)/pending(待审批)/active(进行中)/completed(已完成)/offline(已下架)';
COMMENT ON COLUMN help_requests.delist_reason IS '统一下架原因：AI审核原因、管理员驳回/下架原因、用户自行下架原因';
COMMENT ON COLUMN help_requests.is_proxy      IS '是否物业代发：false(否)/true(是)';
COMMENT ON COLUMN help_requests.location      IS '求助地点';
COMMENT ON COLUMN help_requests.created_at    IS '创建时间';
COMMENT ON COLUMN help_requests.updated_at    IS '更新时间';

-- =============================================================================
-- 8. 帮忙申请表
-- =============================================================================
CREATE TABLE IF NOT EXISTS help_applications (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 申请ID
    help_id       BIGINT      NOT NULL REFERENCES help_requests(id),          -- 求助ID
    helper_id     BIGINT      NOT NULL REFERENCES users(id),                  -- 帮忙者用户ID
    note          VARCHAR(200),                                               -- 申请备注，最多200字
    status        VARCHAR(20) NOT NULL DEFAULT 'pending',                    -- 状态：pending(待确认)/accepted(已接受)/completed(已完成)/rejected(已拒绝)
    completed_at  TIMESTAMP,                                                  -- 完成时间
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at    TIMESTAMP   NOT NULL DEFAULT NOW()                          -- 更新时间
);
COMMENT ON TABLE  help_applications             IS '帮忙申请表，C端用户申请帮忙（接单）记录';
COMMENT ON COLUMN help_applications.id          IS '申请ID（自增主键）';
COMMENT ON COLUMN help_applications.help_id     IS '求助ID，外键→help_requests.id';
COMMENT ON COLUMN help_applications.helper_id   IS '帮忙者用户ID，外键→users.id';
COMMENT ON COLUMN help_applications.note        IS '申请备注，申请时填写的说明，最多200字';
COMMENT ON COLUMN help_applications.status      IS '状态：pending(待确认)/accepted(已接受)/completed(已完成)/rejected(已拒绝)';
COMMENT ON COLUMN help_applications.completed_at IS '完成时间';
COMMENT ON COLUMN help_applications.created_at  IS '创建时间';
COMMENT ON COLUMN help_applications.updated_at  IS '更新时间';

-- =============================================================================
-- 9. 借入申请表
-- =============================================================================
CREATE TABLE IF NOT EXISTS borrow_requests (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 借入申请ID
    idle_id         BIGINT      NOT NULL REFERENCES idle_items(id),             -- 物品ID
    borrower_id     BIGINT      NOT NULL REFERENCES users(id),                  -- 借入者用户ID
    duration_type   VARCHAR(10) NOT NULL,                                      -- 借入时长类型：hour(小时)/day(天)
    duration_days   INTEGER     NOT NULL,                                      -- 借入时长值（数字）
    note            VARCHAR(200),                                               -- 申请备注，最多200字
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',                    -- 状态：pending(待确认)/approved(已同意)/active(进行中)/returned(已归还)/completed(已完成)/rejected(已拒绝)
    handoff_photos  TEXT,                                                       -- 交接照片URL（JSON数组格式）
    approved_at     TIMESTAMP,                                                  -- 审批通过时间（物主同意借出时设置）
    returned_at     TIMESTAMP,                                                  -- 归还完成时间（任意一方确认归还时设置）
    return_status   VARCHAR(20),                                               -- 归还状态：ontime(按时归还)/delayed(逾期归还)/not_returned(未归还)
    return_note     VARCHAR(200),                                               -- 归还备注，最多200字
    damage_type     VARCHAR(20),                                               -- 损坏类型：normal(正常损耗)/severe(非正常损坏)/broken(完全损坏)
    damage_note     VARCHAR(200),                                               -- 损坏说明，最多200字
    is_on_time      BOOLEAN,                                                   -- 是否按时归还：false(逾期)/true(按时)
    return_photos   TEXT,                                                       -- 归还照片URL（JSON数组格式）
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at      TIMESTAMP   NOT NULL DEFAULT NOW()                          -- 更新时间
);
COMMENT ON TABLE  borrow_requests               IS '借入申请表，C端用户申请借入闲置物品的记录';
COMMENT ON COLUMN borrow_requests.id            IS '借入申请ID（自增主键）';
COMMENT ON COLUMN borrow_requests.idle_id       IS '物品ID，外键→idle_items.id';
COMMENT ON COLUMN borrow_requests.borrower_id   IS '借入者用户ID，外键→users.id';
COMMENT ON COLUMN borrow_requests.duration_type IS '借入时长类型：hour(小时)/day(天)';
COMMENT ON COLUMN borrow_requests.duration_days IS '借入时长值（数字），如借3天=3';
COMMENT ON COLUMN borrow_requests.note          IS '申请备注，申请时填写的说明，最多200字';
COMMENT ON COLUMN borrow_requests.status        IS '状态：pending(待确认)/approved(已同意)/active(进行中)/returned(已归还)/completed(已完成)/rejected(已拒绝)';
COMMENT ON COLUMN borrow_requests.handoff_photos IS '交接照片URL（JSON数组格式）';
COMMENT ON COLUMN borrow_requests.approved_at  IS '审批通过时间（物主同意借出时设置）';
COMMENT ON COLUMN borrow_requests.returned_at  IS '归还完成时间（任意一方确认归还时设置）';
COMMENT ON COLUMN borrow_requests.return_status IS '归还状态：ontime(按时归还)/delayed(逾期归还)/not_returned(未归还)';
COMMENT ON COLUMN borrow_requests.return_note   IS '归还备注，最多200字';
COMMENT ON COLUMN borrow_requests.damage_type   IS '损坏类型：normal(正常损耗)/severe(非正常损坏)/broken(完全损坏)';
COMMENT ON COLUMN borrow_requests.damage_note   IS '损坏说明，最多200字';
COMMENT ON COLUMN borrow_requests.is_on_time    IS '是否按时归还：false(逾期)/true(按时)';
COMMENT ON COLUMN borrow_requests.return_photos IS '归还照片URL（JSON数组格式）';
COMMENT ON COLUMN borrow_requests.created_at    IS '创建时间';
COMMENT ON COLUMN borrow_requests.updated_at    IS '更新时间';

-- =============================================================================
-- 10. 通知表
-- =============================================================================
CREATE TABLE IF NOT EXISTS notifications (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 通知ID
    user_id       BIGINT       NOT NULL REFERENCES users(id),                  -- 接收用户ID
    type          VARCHAR(30)  NOT NULL,                                      -- 通知类型：audit_result(审核结果)/violation(违规通知)/chat(聊天消息)/borrow(借入通知)/help(帮忙通知)
    title         VARCHAR(100) NOT NULL,                                      -- 通知标题
    content       TEXT,                                                       -- 通知内容（系统生成，不限长度）
    related_id    BIGINT,                                                      -- 关联实体ID
    is_read       BOOLEAN      NOT NULL DEFAULT FALSE,                        -- 是否已读：false(未读)/true(已读)
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()                         -- 创建时间
);
COMMENT ON TABLE  notifications                IS '通知表，推送给用户的消息通知（C端通知页面待实现）';
COMMENT ON COLUMN notifications.id             IS '通知ID（自增主键）';
COMMENT ON COLUMN notifications.user_id        IS '接收用户ID，外键→users.id';
COMMENT ON COLUMN notifications.type           IS '通知类型：audit_result(审核结果)/violation(违规通知)/chat(聊天消息)/borrow(借入通知)/help(帮忙通知)';
COMMENT ON COLUMN notifications.title          IS '通知标题';
COMMENT ON COLUMN notifications.content        IS '通知内容（系统生成，不限长度）';
COMMENT ON COLUMN notifications.related_id     IS '关联实体ID，用于跳转到对应帖子/申请';
COMMENT ON COLUMN notifications.is_read        IS '是否已读：false(未读)/true(已读)';
COMMENT ON COLUMN notifications.created_at     IS '创建时间';

-- =============================================================================
-- 11. 操作日志表
-- =============================================================================
CREATE TABLE IF NOT EXISTS operation_logs (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 日志ID
    admin_id      BIGINT      NOT NULL REFERENCES users(id),                  -- 管理员ID
    tenant_id     BIGINT      NOT NULL REFERENCES tenants(id),               -- 所属小区ID
    action        VARCHAR(50) NOT NULL,                                      -- 操作动作
    target_type   VARCHAR(30),                                               -- 操作对象类型
    target_id     BIGINT,                                                     -- 操作对象ID
    detail        TEXT,                                                       -- 操作详情（JSON格式）
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW()                         -- 创建时间
);
COMMENT ON TABLE  operation_logs                IS '操作日志表，记录B端管理员的所有管理操作';
COMMENT ON COLUMN operation_logs.id             IS '日志ID（自增主键）';
COMMENT ON COLUMN operation_logs.admin_id       IS '管理员ID，外键→users.id';
COMMENT ON COLUMN operation_logs.tenant_id     IS '所属小区ID，外键→tenants.id，用于按小区导出操作日志';
COMMENT ON COLUMN operation_logs.action         IS '操作动作：审核认证/下架物品/封禁用户/删除帖子等';
COMMENT ON COLUMN operation_logs.target_type    IS '操作对象类型：user(住户)/idle(闲置物品)/help(技能求助)';
COMMENT ON COLUMN operation_logs.target_id      IS '操作对象ID';
COMMENT ON COLUMN operation_logs.detail         IS '操作详情（JSON格式），存储操作前后数据';
COMMENT ON COLUMN operation_logs.created_at     IS '创建时间';

-- =============================================================================
-- 12. 评分表
-- =============================================================================
CREATE TABLE IF NOT EXISTS ratings (
    id                  BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 评分ID
    borrow_id           BIGINT    REFERENCES borrow_requests(id),                 -- 借入申请ID
    help_application_id BIGINT    REFERENCES help_applications(id),               -- 帮忙申请ID
    from_user_id        BIGINT    NOT NULL REFERENCES users(id),                  -- 评分人用户ID
    to_user_id          BIGINT    NOT NULL REFERENCES users(id),                  -- 被评分人用户ID
    score               INTEGER   NOT NULL DEFAULT 5,                            -- 综合评分：1(非常差)/2(较差)/3(一般)/4(良好)/5(非常好)
    feedback            VARCHAR(500),                                              -- 互助感想文本
    created_at          TIMESTAMP NOT NULL DEFAULT NOW()                         -- 创建时间
);
COMMENT ON TABLE  ratings                      IS '评分表，借入/帮忙完成后互相评价';
COMMENT ON COLUMN ratings.id                   IS '评分ID（自增主键）';
COMMENT ON COLUMN ratings.borrow_id            IS '借入申请ID，外键→borrow_requests.id（与help_application_id二选一）';
COMMENT ON COLUMN ratings.help_application_id  IS '帮忙申请ID，外键→help_applications.id（与borrow_id二选一）';
COMMENT ON COLUMN ratings.from_user_id         IS '评分人用户ID，外键→users.id';
COMMENT ON COLUMN ratings.to_user_id           IS '被评分人用户ID，外键→users.id';
COMMENT ON COLUMN ratings.score                IS '综合评分：1(非常差)/2(较差)/3(一般)/4(良好)/5(非常好)，住户综合各维度自行考量';
COMMENT ON COLUMN ratings.feedback             IS '互助感想文本，选填，最多500字符';
COMMENT ON COLUMN ratings.created_at           IS '创建时间';

-- =============================================================================
-- 13. 聊天消息表
-- =============================================================================
CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 消息ID
    session_id      VARCHAR(255) NOT NULL,                                      -- 会话标识：IDLE_42_3_7 / HELP_42_3_7 / USER_3_7
    from_user_id    BIGINT       NOT NULL REFERENCES users(id),                 -- 发送方用户ID
    to_user_id      BIGINT       NOT NULL REFERENCES users(id),                 -- 接收方用户ID
    content         TEXT,                                                        -- 消息正文，撤回后置为NULL
    message_type    VARCHAR(20)  NOT NULL DEFAULT 'text',                        -- 消息类型：text(文本)/system(系统消息)
    status          VARCHAR(20)  NOT NULL DEFAULT 'sent',                        -- 消息状态：sent(已发送)/delivered(已送达)/read(已读)
    recalled_at     TIMESTAMP,                                                   -- 撤回时间，NULL=未撤回
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),                         -- 创建时间
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW()                          -- 更新时间
);
COMMENT ON TABLE  messages                      IS '聊天消息表，C端住户间私密通信记录';
COMMENT ON COLUMN messages.id                   IS '消息ID（自增主键）';
COMMENT ON COLUMN messages.session_id           IS '会话标识，三段式格式：TYPE_postId_smallerId_largerId';
COMMENT ON COLUMN messages.from_user_id         IS '发送方用户ID，外键→users.id';
COMMENT ON COLUMN messages.to_user_id           IS '接收方用户ID，外键→users.id';
COMMENT ON COLUMN messages.content              IS '消息正文；撤回后置为NULL，客户端渲染"消息已撤回"';
COMMENT ON COLUMN messages.message_type         IS '消息类型：text(文本)/system(系统消息)';
COMMENT ON COLUMN messages.status               IS '消息状态：sent(已发送)/delivered(已送达)/read(已读)';
COMMENT ON COLUMN messages.recalled_at          IS '撤回时间，NULL=未撤回，撤回后content置NULL';
COMMENT ON COLUMN messages.created_at           IS '创建时间';
COMMENT ON COLUMN messages.updated_at           IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_msg_session_time ON messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_msg_from_user    ON messages(from_user_id);
CREATE INDEX IF NOT EXISTS idx_msg_to_user      ON messages(to_user_id);

-- =============================================================================
-- 14. 导出日志表
-- =============================================================================
CREATE TABLE IF NOT EXISTS export_logs (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 日志ID
    admin_id         BIGINT       NOT NULL REFERENCES users(id),                   -- 导出操作人ID
    tenant_id        BIGINT       NOT NULL REFERENCES tenants(id),                -- 所属小区ID
    export_format    VARCHAR(10)  NOT NULL DEFAULT 'xlsx',                        -- 导出格式：xlsx
    selected_options TEXT         NOT NULL,                                        -- 勾选项目（JSON数组），如 ["residents","posts"]
    date_range_start VARCHAR(10),                                                  -- 筛选开始日期（yyyy-MM-dd）
    date_range_end   VARCHAR(10),                                                  -- 筛选结束日期（yyyy-MM-dd）
    residents_count  INTEGER      NOT NULL DEFAULT 0,                             -- 住户清单记录数
    posts_count      INTEGER      NOT NULL DEFAULT 0,                             -- 发布记录数
    borrows_count    INTEGER      NOT NULL DEFAULT 0,                             -- 互借记录数
    helps_count      INTEGER      NOT NULL DEFAULT 0,                             -- 互助记录数（技能求助）
    removals_count   INTEGER      NOT NULL DEFAULT 0,                             -- 下架记录数
    ratings_count    INTEGER      NOT NULL DEFAULT 0,                             -- 评分记录数
    file_name        VARCHAR(200) NOT NULL,                                        -- 生成的文件名
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW()                          -- 创建时间
);
COMMENT ON TABLE  export_logs                       IS '导出日志表，记录每次B端数据导出操作';
COMMENT ON COLUMN export_logs.id                    IS '日志ID（自增主键）';
COMMENT ON COLUMN export_logs.admin_id              IS '导出操作人ID，外键→users.id';
COMMENT ON COLUMN export_logs.tenant_id             IS '所属小区ID，外键→tenants.id';
COMMENT ON COLUMN export_logs.export_format         IS '导出文件格式：xlsx';
COMMENT ON COLUMN export_logs.selected_options      IS '勾选的导出项目（JSON数组字符串），如 ["residents","posts","borrows"]';
COMMENT ON COLUMN export_logs.date_range_start      IS '筛选开始日期（yyyy-MM-dd），NULL表示不限';
COMMENT ON COLUMN export_logs.date_range_end        IS '筛选结束日期（yyyy-MM-dd），NULL表示不限';
COMMENT ON COLUMN export_logs.residents_count       IS '住户清单Sheet记录数';
COMMENT ON COLUMN export_logs.posts_count           IS '发布记录Sheet记录数';
COMMENT ON COLUMN export_logs.borrows_count         IS '互借记录Sheet记录数';
COMMENT ON COLUMN export_logs.helps_count           IS '互助记录（技能求助）Sheet记录数';
COMMENT ON COLUMN export_logs.removals_count        IS '下架记录Sheet记录数';
COMMENT ON COLUMN export_logs.ratings_count         IS '评分数据Sheet记录数';
COMMENT ON COLUMN export_logs.file_name             IS '生成的文件名（不含路径），如 export_2026-07-01_2026-07-25.xlsx';
COMMENT ON COLUMN export_logs.created_at            IS '创建时间';
